spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:mysql://localhost:3306/quickcab
    username: root
    password: Dsov@0506
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
